trigger:
- main

pool: ROG-pool

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- script: pip install -r sdk/dev-requirements.txt
  displayName: 'pip install notebook reqs'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- script: pip install --pre azure-ai-ml mldesigner mltable azure-ai-ml==0.1.0.b6
  displayName: 'set up sdk'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      az extension add -n ml -y
      # rc install - uncomment and adjust below to run all tests on a CLI release candidate
      # az extension remove -n ml
      
      # Use a daily build
      # az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2-public/ml-2.6.0-py3-none-any.whl --yes
       
      # <set_variables>
      GROUP="azureml-examples"
      LOCATION="eastus"
      WORKSPACE="main"
      # </set_variables>
      
      # <az_configure_defaults>
      az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
      # </az_configure_defaults>
  displayName: 'set up CLI'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(SUBSCRIPTION_ID)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
           sed -i -e "s/<SUBSCRIPTION_ID>/$(SUBSCRIPTION_ID)/g" sklearn-diabetes.ipynb
           sed -i -e "s/<RESOURCE_GROUP>/$(RESOURCE_GROUP)/g" sklearn-diabetes.ipynb
           sed -i -e "s/<AML_WORKSPACE_NAME>/$(AZUREML_WORKSPACE_NAME)/g" sklearn-diabetes.ipynb
           sed -i -e "s/DefaultAzureCredential/AzureCliCredential/g" sklearn-diabetes.ipynb
           papermill -k python sklearn-diabetes.ipynb sklearn-diabetes.output.ipynb
    workingDirectory: 'sdk/jobs/single-step/scikit-learn/diabetes'