trigger:
- main

pool: ROG-pool

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- script: pip install -r sdk/dev-requirements.txt
  displayName: 'pip install notebook reqs'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
- script: pip install --pre azure-ai-ml mldesigner mltable azure-ai-ml==0.1.0.b6
  displayName: 'set up sdk'

- task: Bash@3
  inputs:
    filePath: 'cli/setup.sh'
  displayName: 'set up CLI'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'DP100-Test'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      (Get-Content -pathsklearn-diabetes.ipynb -Raw) -replace '<SUBSCRIPTION_ID>','$(SUBSCRIPTION_ID)'
      (Get-Content -pathsklearn-diabetes.ipynb -Raw) -replace '<RESOURCE_GROUP>','$(RESOURCE_GROUP)'
      (Get-Content -pathsklearn-diabetes.ipynb -Raw) -replace '<AML_WORKSPACE_NAME>','$(AZUREML_WORKSPACE_NAME)'
      (Get-Content -pathsklearn-diabetes.ipynb -Raw) -replace 'DefaultAzureCredential','AzureCliCredential'      
      papermill -k python sklearn-diabetes.ipynb sklearn-diabetes.output.ipynb
    workingDirectory: 'sdk/jobs/single-step/scikit-learn/diabetes'